services:
  policy-engine:
    build: ./policy-engine
    container_name: policy-engine
    env_file:
      - .env
    environment:
      NODE_SERVICE_URL: http://node-drizzle:3000/internal
    ports:
      - "8001:8001"
    depends_on:
      - node-drizzle

  node-drizzle:
    build: ./node-drizzle
    container_name: node-drizzle
    env_file:
      - .env
    environment:
      PORT: 3000
    ports:
      - "3000:3000"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - policy-engine
    env_file:
      - .env
    environment:
      POLICY_ENGINE_URL: http://policy-engine:8001
      LLM_API_KEY: dummy_key
    ports:
      - "8000:8000"
